using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using FootballMarket.Core.Models;

namespace FootballMarket.DataAccess
{
    public class PlayerRepository : IPlayerRepository
    {
        private readonly List<Player> _players;

        public PlayerRepository()
        {
            _players = new List<Player>
            {
                new Player { Id = 1, Name = "Cristiano Ronaldo", Team = "Juventus", MarketPrice = 100000000, Image = "https://www.realmadrid.com/img/vertical_380px/cristiano_550x650.jpg", PlayerBio = "Cristiano Ronaldo dos Santos Aveiro GOIH ComM (Portuguese pronunciation: [kɾiʃˈtjɐnu ʁɔˈnaɫdu]; born 5 February 1985) is a Portuguese professional footballer who plays as a forward for Serie A club Juventus and captains the Portugal national team. Often considered the best player in the world and widely regarded as one of the greatest players of all time, Ronaldo has won five Ballon d'Or awards[note 3] and four European Golden Shoes, both of which are records for a European player. He has won 31 major trophies in his career, including seven league titles, five UEFA Champions Leagues, one UEFA European Championship, and one UEFA Nations League title. Ronaldo holds the records for the most goals (134) and assists (41) in the history of the UEFA Champions League.[10] He is one of the few recorded players to have made over 1,000 professional career appearances and has scored over 780 senior career goals for club and country.[11] He is also the second male to score 100 international goals and the first European man to achieve the feat."},
                new Player { Id = 2, Name = "Lionel Messi", Team = "Barcelona", MarketPrice = 80000000, Image = "https://www.fcbarcelona.com/photo-resources/2020/10/08/9518739f-39fa-4729-b455-27a95966d5b4/mini_messi-copia.png?width=670&height=790", PlayerBio = "Lionel Andrés Messi[note 1] (Spanish pronunciation: [ljoˈnel anˈdɾes ˈmesi] (About this soundlisten);[A] born 24 June 1987) is an Argentine professional footballer who plays as a forward and captains both the Spanish club Barcelona and the Argentina national team. Often considered as the best player in the world and widely regarded as one of the greatest players of all time, Messi has won a record six Ballon d'Or awards[note 2] and a record six European Golden Shoes. He has spent his entire professional career with Barcelona, where he has won a club-record 34 trophies, including ten La Liga titles, six Copa del Rey titles and four UEFA Champions Leagues. A prolific goalscorer and creative playmaker, Messi holds the records for most goals in La Liga (463), a La Liga and European league season (50), most hat-tricks in La Liga (36) and the UEFA Champions League (8), and most assists in La Liga (187), a La Liga and European league season (21)[9] and the Copa América (12). He has scored over 750 senior career goals for club and country, and has the most goals ever by a player for a single club."},
                new Player { Id = 3, Name = "Antuan Griezman", Team = "Barcelona", MarketPrice = 70000000, Image = "https://assets.laliga.com/squad/2020/t178/p76650/2048x2048/p76650_t178_2020_1_003_000.png", PlayerBio = "Antoine Griezmann (French pronunciation: ​[ɑ̃twan ɡʁijɛzman];[4] born 21 March 1991) is a French professional footballer who plays as a forward for Spanish club Barcelona and the France national team. He is often considered to be one of the best forwards in the world. Born and raised in Mâcon, Griezmann began his senior career with Real Sociedad in 2009, with whom he won the Segunda División title in his first season. In 2014, he joined Atlético Madrid for a then-club record €30 million, where he broke the club's scoring record for a debut season and was named in the 2014–15 La Liga Team of the Season. He was voted La Liga Best Player in 2016, and finished third for the 2016 Ballon d'Or and 2016 Best FIFA Men's Player.[5] He finished third and sixth respectively for the awards in 2018,[6] as he helped Atlético Madrid win the UEFA Europa League, scoring twice in the final. Griezmann also won the 2014 Supercopa de España and 2018 UEFA Super Cup, and ranks as the club's fifth-highest goalscorer.[7] In 2019, Griezmann signed for league rivals Barcelona in a transfer worth €120 million, becoming the joint-fourth most expensive footballer ever.[8]"},
                new Player { Id = 4, Name = "Kilian Mbappe", Team = "PSG", MarketPrice = 150000000, Image = "https://images-na.ssl-images-amazon.com/images/I/61q1fZgy1EL._AC_SL1118_.jpg", PlayerBio = "Kylian Mbappé Lottin (born 20 December 1998) is a French professional footballer who plays as a forward for Ligue 1 club Paris Saint-Germain and the France national team. Widely considered as one of the best players in the world, he is known for his dribbling, explosive speed, and clinical finishing.Mbappé began his senior career with Ligue 1 club Monaco, making his professional debut in 2015, aged 16. With them, he won a Ligue 1 title, Ligue 1 Young Player of the Year, and the Golden Boy award. In 2017, he signed for league rivals Paris Saint - Germain on an initial loan, which was made permanent in 2018 in a transfer worth €180 million, making him both the second - most expensive player and most expensive teenager.[4] There, Mbappé won three Ligue 1 titles, two Coupe de France titles, was named Ligue 1 Player of the Year, and has finished as Ligue 1 top scorer twice.He is also the third - highest goalscorer in the club's history."},
                new Player { Id = 5, Name = "Romelu Lukaku", Team = "Inter", MarketPrice = 120000000, Image = "https://www.inter.it/html/img/giocatori/profilo-schede/2020-21/G1034.png", PlayerBio = "Romelu Menama Lukaku Bolingoli (Dutch pronunciation: [ˈroːmeːlu luˈkaːku]; born 13 May 1993) is a Belgian professional footballer who plays as a striker for Serie A club Inter Milan and the Belgium national team.Born in Antwerp, he began his professional career at Belgian Pro League club Anderlecht in 2009, where he made his senior debut, at age 16. He won the league's top goalscorer, the league championship and the Belgian Ebony Shoe there. He signed for English side Chelsea in 2011, but featured sparingly in his first season and joined West Bromwich Albion on loan in 2012. He helped them to an unexpected eighth-place finish in the 2012–13 season and ahead of the 2013–14 season, he joined Everton on loan. After helping Everton reach a club-record points tally, he joined the team in a permanent deal worth a club-record fee of £28 million in 2014. He was named in the 2016–17 PFA Team of the Year, Lukaku signed for Manchester United in 2017, for an initial fee of £75 million.[4] After two seasons in Manchester Lukaku's relationship with the club deteriorated. Lukaku failed to return for pre - season training, was fined, and subsequently signed for Inter Milan in August 2019, for a reported club record €80 million.[5]"},
                new Player { Id = 6, Name = "Erling Haaland ", Team = "Borussia Dortmund", MarketPrice = 130000000, Image = "https://bulinews.com/i/640/1986.jpg", PlayerBio = "Erling Braut Haaland (né Håland, [ˈhòːlɑn]; born 21 July 2000) is a Norwegian professional footballer who plays as a striker for Bundesliga club Borussia Dortmund and the Norway national team. A prolific goalscorer, he is recognised for his pace, athleticism, strength and precise off-the-ball movement, and he has been considered as one of the best young footballers in the world.[5][6]"},
                new Player { Id = 7, Name = "Zlatan Ibrahimovich", Team = "Milan", MarketPrice = 15000000, Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyTby3sYPOjBmLcA9gMhHVGVXm-r4YbDxy2A&usqp=CAU", PlayerBio = "Zlatan Ibrahimović (Swedish pronunciation: [ˈslǎːtan ɪbraˈhǐːmovɪtɕ]; Bosnian pronunciation: [zlǎtan ibraxǐːmoʋitɕ]; born 3 October 1981) is a Swedish professional footballer who plays as a striker for Serie A club Milan. Ibrahimović is widely regarded as one of the best strikers of all time.[3][4][5][6][7] He is one of the most decorated active footballers in the world,[a] having won 31 trophies in his career.[10] He has scored over 570 career goals, including more than 500 club goals,[11] and has scored in each of the last four decades.[12][13]"},
                new Player { Id = 8, Name = "Kevin De Bruyne", Team = "Manchester City", MarketPrice = 75000000, Image = "https://resources.premierleague.com/premierleague/photos/players/250x250/p61366.png", PlayerBio = "Kevin De Bruyne (Dutch pronunciation: [ˈkɛvɪn də ˈbrœynə]; born 28 June 1991) is a Belgian professional footballer who plays as a midfielder for Premier League club Manchester City, where he is vice-captain, and the Belgian national team. Recognized for his exceptional passing, shooting and dribbling abilities, he is widely considered to be one of the best players in the world and has often been described as a complete midfielder."},
                new Player { Id = 9, Name = "Neymar", Team = "PSG", MarketPrice = 180000000, Image = "https://1vs1-7f65.kxcdn.com/img/players/players/neymar-da-silva-santos-junior_9732_212-ub-800.png", PlayerBio = "Neymar da Silva Santos Júnior (Brazilian Portuguese: [nejˈmaʁ dɐ ˈsiwvɐ ˈsɐ̃tus ˈʒũɲoʁ]; born 5 February 1992), known as Neymar, is a Brazilian professional footballer who plays as a forward for Ligue 1 club Paris Saint-Germain and the Brazil national team. He is widely regarded as one of the best players in the world.[7][8]Neymar came into prominence at Santos, where he made his professional debut aged 17. He helped the club win two successive Campeonato Paulista championships, a Copa do Brasil, and the 2011 Copa Libertadores; the latter being Santos' first since 1963. Neymar was twice named the South American Footballer of the Year, in 2011 and 2012, and soon relocated to Europe to join Barcelona. As part of Barcelona's attacking trio with Lionel Messi and Luis Suárez, he won the continental treble of La Liga, the Copa del Rey, and the UEFA Champions League, and finished third for the FIFA Ballon d'Or in 2015 for his performances. He then attained a domestic double in the 2015–16 season. In 2017, Neymar transferred to Paris Saint-Germain in a move worth €222 million, making him the most expensive player ever.[note 1] In France, Neymar won three league titles, two Coupe de France, and two Coupe de la Ligue, which included a domestic treble and being voted Ligue 1 Player of the Year in his debut season.[11] Neymar helped PSG attain a domestic quadruple in the 2019–20 season, and led the club to its first ever Champions League Final."},
            };
        }

        public IEnumerable<Player> GetPlayers(string query)
        {
            if (String.IsNullOrWhiteSpace(query))
            {
                return _players;
            }
            return _players.Where(p => p.Name.ToLower().Contains(query.ToLower()));
        }

        public Player GetPlayer(int id)
        {
            return _players.FirstOrDefault(p => p.Id == id);
        }
    }
}
